### ISSUE TITLE
Testing if the aliases in Wikidata and in MusicBrainz are the same.

### ISSUE THREAD

**Issue by Yueqiao12Zhang** [DDMAL/linkedmusic-datalake#102]
Tested segment:
```
https://musicbrainz.org/genre/f23423bb-3bfe-4e90-b7df-ab2479e82e7d,kalon'ny fahiny,,Q114702536
https://musicbrainz.org/genre/89559e4a-22ad-43ac-a83d-07189b954a6b,kaneka,,Q3192617
https://musicbrainz.org/genre/d5541aec-ffc2-4bc5-834d-d72f0718996a,kankyō ongaku,,Q112159506
https://musicbrainz.org/genre/93cdfa86-adef-4a9a-b9ce-970decf7aedd,kantan chamorrita,,Q6365333
https://musicbrainz.org/genre/3f2875dd-4f53-41a0-95fe-a19a21a06a72,kanto,,Q6365528
https://musicbrainz.org/genre/7beb296c-76bf-41b7-90e7-7613d167134a,kantruem,,Q4925966
https://musicbrainz.org/genre/b32532d2-0006-49cd-957f-4011e33881d1,kapuka,,Q4943457
https://musicbrainz.org/genre/57a6dcc1-c3cd-4ce1-9fb2-e1783992a683,kaseko,Suriname,Q610022
https://musicbrainz.org/genre/c1f813d2-d21f-4eda-85e3-e8bfac92b3e1,kasékò,Guiana,Q60722009
https://musicbrainz.org/genre/35f85622-978c-4bf4-b5e4-722394d474f1,kawaii future bass,,Q106577542
https://musicbrainz.org/genre/5319fada-431d-4b16-ac6f-37e24b2201b5,kawaii metal,,Q16096634
https://musicbrainz.org/genre/7054e8e2-7c7b-4432-83b9-93423b361792,kayōkyoku,,Q1418683
https://musicbrainz.org/genre/5ac69ee4-befe-438f-b1ea-a3f8af69bc2f,kecak,,Q1737691
https://musicbrainz.org/genre/98c1a0fe-f460-4521-bcff-760d719cd958,keroncong,,Q1930107
https://musicbrainz.org/genre/60ada19f-c6af-49db-8fbf-3479e70f6689,kete,,Q124399721
https://musicbrainz.org/genre/e32aa6be-e8aa-425a-950e-8478690cc45d,ketuk tilu,,Q20427333
https://musicbrainz.org/genre/ecac48dc-1b01-4793-956d-5d6905105808,khrueang sai,,Q6629917
https://musicbrainz.org/genre/b8bf0e96-4961-488b-a5f7-4cfbb9afa17c,khyal,,Q62128
https://musicbrainz.org/genre/d04c4dcd-8e79-4dc1-b24a-000b3dd861ad,kidandali,,Q6404580
https://musicbrainz.org/genre/083a536e-41b5-4639-9589-fca13ef5dd82,kidumbak,,Q3815106
https://musicbrainz.org/genre/22281d15-2edd-4610-8336-444c1e50d0e9,kilapanga,,Q108845022
https://musicbrainz.org/genre/c5aa3e2c-b7ad-4f52-adc3-53af8c9913f1,kirtan,,Q947155
https://musicbrainz.org/genre/5c8b654c-0f2b-40d5-990b-e070a527b1df,kizomba,,Q1597549
https://musicbrainz.org/genre/5d1f5abe-3e6b-45fe-bdad-8114b5c275fe,klapa,,Q1428470
https://musicbrainz.org/genre/77f95127-ba44-4211-8d69-36bd53391ec8,kleinkunst,,Q106917640
https://musicbrainz.org/genre/06eeec6e-f389-4783-b601-909bb10bd04e,klezmer,,Q212944
https://musicbrainz.org/genre/94739e90-28bb-4457-944f-50415f2484a8,kliningan,,Q6421060
https://musicbrainz.org/genre/2ab6c422-3a84-41d8-986b-52aa94ad7464,konnakol,,Q3521984
https://musicbrainz.org/genre/8040d6f5-c378-4ef3-9d3f-5585a18c5bf2,koplo,,Q31174954
```

**Comment by Yueqiao12Zhang** [comment]
https://musicbrainz.org/genre/f23423bb-3bfe-4e90-b7df-ab2479e82e7d,kalon'ny fahiny,,Q114702536 MB: no alias WKD: no alias
https://musicbrainz.org/genre/89559e4a-22ad-43ac-a83d-07189b954a6b,kaneka,,Q3192617 MB: no alias WKD: no alias
https://musicbrainz.org/genre/d5541aec-ffc2-4bc5-834d-d72f0718996a,kankyō ongaku,,Q112159506 MB: no alias WKD: no alias
https://musicbrainz.org/genre/93cdfa86-adef-4a9a-b9ce-970decf7aedd,kantan chamorrita,,Q6365333 MB: no alias WKD: ayotte, chamorrita singing
https://musicbrainz.org/genre/3f2875dd-4f53-41a0-95fe-a19a21a06a72,kanto,,Q6365528 MB: no alias WKD: no alias
https://musicbrainz.org/genre/7beb296c-76bf-41b7-90e7-7613d167134a,kantruem,,Q4925966 MB: kantrum WKD: kantrum/kantruem
https://musicbrainz.org/genre/b32532d2-0006-49cd-957f-4011e33881d1,kapuka,,Q4943457 MB: boomba music WKD: boomba music/kapuka
https://musicbrainz.org/genre/57a6dcc1-c3cd-4ce1-9fb2-e1783992a683,kaseko,Suriname,Q610022 MB: no alias WKD: no alias
https://musicbrainz.org/genre/c1f813d2-d21f-4eda-85e3-e8bfac92b3e1,kasékò,Guiana,Q60722009 MB: no alias WKD: no alias
https://musicbrainz.org/genre/35f85622-978c-4bf4-b5e4-722394d474f1,kawaii future bass,,Q106577542 MB: no alias WKD: kawaii bass
https://musicbrainz.org/genre/5319fada-431d-4b16-ac6f-37e24b2201b5,kawaii metal,,Q16096634 MB: no alias WKD: cute metal, idol metal, kawaiicore, Kawaii metal
https://musicbrainz.org/genre/7054e8e2-7c7b-4432-83b9-93423b361792,kayōkyoku,,Q1418683 MB: kayokyoku WKD: kayō, kayou, kayoukyoku, shōwa era pop, standard Japanese pop, traditional J-pop, kayo-kyoku, kayokyoku
https://musicbrainz.org/genre/5ac69ee4-befe-438f-b1ea-a3f8af69bc2f,kecak,,Q1737691 MB: no alias WKD: Ketjak, Kechak
https://musicbrainz.org/genre/98c1a0fe-f460-4521-bcff-760d719cd958,keroncong,,Q1930107 MB: kroncong, keroncong, krontjong WKD: keroncong, krontjong
https://musicbrainz.org/genre/60ada19f-c6af-49db-8fbf-3479e70f6689,kete,,Q124399721 MB: no alias WKD: no alias
https://musicbrainz.org/genre/e32aa6be-e8aa-425a-950e-8478690cc45d,ketuk tilu,,Q20427333 MB: no alias WKD: no alias
https://musicbrainz.org/genre/ecac48dc-1b01-4793-956d-5d6905105808,khrueang sai,,Q6629917 MB: no alias WKD: Wong khrueang sai, Khruang sai, Khryang sai
https://musicbrainz.org/genre/b8bf0e96-4961-488b-a5f7-4cfbb9afa17c,khyal,,Q62128 MB: no alias WKD: Khayal
https://musicbrainz.org/genre/d04c4dcd-8e79-4dc1-b24a-000b3dd861ad,kidandali,,Q6404580 MB: no alias WKD: no alias
https://musicbrainz.org/genre/083a536e-41b5-4639-9589-fca13ef5dd82,kidumbak,,Q3815106 MB: kidumbaki, kitaarab WKD: kidumbak, kitaarab
https://musicbrainz.org/genre/22281d15-2edd-4610-8336-444c1e50d0e9,kilapanga,,Q108845022 MB: no alias WKD: no alias

**Comment by Yueqiao12Zhang** [comment]
@fujinaga

**Comment by fujinaga** [comment]
Does it look like that every MB aliases are entered in Wikidata?
Can you check 10 more genres that have MB aliases and see if they are indeed in Wikidata?
If we can conclude that all MB aliases are in Wikidata then we don't need to include the MB aliases in our RDF graph.

**Comment by Yueqiao12Zhang** [comment]
It doesn't seems like all MB aliases are in Wikidata.
MB: kroncong, keroncong, krontjong WKD: keroncong, krontjong
MB: kidumbaki, kitaarab WKD: kidumbak, kitaarab

**Comment by fujinaga** [comment]
Ok because this situation is fairly rare. Create a separate low-priority  issue to write a script that will add Musicbrainz aliases that are not in Wikidata. We will not add locally in our RDF graph these aliases. You can close this issue (#102).
