### ISSUE TITLE
Modify The Session

### ISSUE THREAD

**Issue by candlecao** [DDMAL/linkedmusic-datalake#118]
Especially modify the properties according to https://github.com/DDMAL/linkedmusic-datalake/issues/98.
Double check and regenerate the RDF.

**Comment by dchiller** [comment]
> Especially modify the properties according to #98.

Could you list those modifications here?

**Comment by candlecao** [comment]
> > Especially modify the properties according to #98.
> 
> Could you list those modifications here?

### 1. Some to be reviewed or questionable:

address-> street address (P6375)
town-> located in the administrative territorial entity (P131)
area-> location (P276)


`"type": "http://www.wikidata.org/prop/direct/P2308",`-> P136.

`"event": "http://www.wikidata.org/prop/direct/P793",`->Just the name of event.



### 2. Some are to be corrected:
2.1
```
    "latitude": "http://www.wikidata.org/prop/direct/P6261"
    "longitude": "http://www.wikidata.org/prop/direct/P6260"
```
P6261,6260 are galactic coordinates. We should use wdt:P625 and put the two attributes's value together:
![Screenshot 2024-08-05 at 11 33 16 AM](https://github.com/user-attachments/assets/bb3d404a-46cf-4358-ac1d-bfc232a83886)

--I just asked ChatGPT and referred to Wikidata Query Service to make sure of that.

2.2  "artist": "http://www.wikidata.org/prop/direct/P5489", -> "http://www.wikidata.org/prop/direct/P50"
and the property value of artist should be the URI. The session has all the URIs respectively for the artists.

2.3 "recording": "https://www.wikidata.org/prop/direct/P51", -> "http://www.wikidata.org/prop/direct/P2561"

2.4 "recording_wiki": "http://www.wikidata.org/prop/direct/P51", -> "http://www.wikidata.org/prop/direct/P2888" exact match

2.5 "tunebooks":"http://www.wikidata.org/entity/Q66382988", -> "https://thesession.org/tunebooks"

### 3. Some are ...
The first column of aliases.csv is the entity of tune. Will the particularity affect our codes?
