### ISSUE TITLE
Account for the reconciliation of properties and types in The Session

### ISSUE THREAD

**Issue by candlecao** [DDMAL/linkedmusic-datalake#122]
This issue follows https://github.com/DDMAL/linkedmusic-datalake/issues/118.

I made a document named "AccountForReconciliation" in the-session-correction branch > csv2rdf > thesession.
@Yueqiao12Zhang  (Because the mapping file in the branch is the newest.)

**Comment by dchiller** [comment]
I can't open the file. Also, why was this file commit ([daa67bb](https://github.com/DDMAL/linkedmusic-datalake/pull/119/commits/daa67bbefa2265eeb8d41b4e456681d71267d08d)) in the history of #118?

**Comment by candlecao** [comment]
Just forget this. If you update the branch right now, you will not find the file again.

**Comment by candlecao** [comment]
And It is removed from the branch associated with "#119" and now rebased at the current branch "AccountForReconciliationOfTheSession".
Sorry, I am a new git hub user. It took me some time to adapt to it.

**Comment by candlecao** [comment]
Hi Ich, @fujinaga , I made a documentation in the file "AccountForReconciliation.ttl" in the branch "AccountForReconciliationOfTheSession". You can navigate to csv2rdf > thesession > AccountForReconciliation.ttl.
Just like this:
![image](https://github.com/user-attachments/assets/a5c4304f-da4e-4793-b4b9-915f430e8150)
