### ISSUE TITLE
Figure out how to express information associated with date, time etc. in RDF? 

### ISSUE THREAD

**Issue by candlecao** [DDMAL/linkedmusic-datalake#143]
For example:
`6/17/2001 5:21:00 AM`
--This should not be rendered as `rdf:literal` or `xsd:string` etc.

We had better consider the factor of time zone.

**Comment by fujinaga** [comment]
I suggest using:
:eventDateTime rdf:type xsd:dateTime ;
               rdf:value "2024-08-14T10:30:00"^^xsd:dateTime .
Or with a time zone:
:eventDateTime rdf:type xsd:dateTime ;
               rdf:value "2024-08-14T10:30:00+02:00"^^xsd:dateTime .

 But with theSession data, we’re not sure of the time zone, I would not use the time zone. Theoretically we can determine the time zone from the location, however.

**Comment by candlecao** [comment]
Yes, you are right. I tried like this:
```
insert data
{
<https://thesession.org/events/11> <http://www.wikidata.org/prop/direct/P580> "2006-06-07T09:30:00"^^xsd:dateTime.
}
```
Then I query with SPARQL:
```
select * where{
<https://thesession.org/events/11> <http://www.wikidata.org/prop/direct/P580> ?o
}
```
The corresponding result is: `2006-06-07T09:30:00` instead of `"2006-06-07T09:30:00"`. It means this format is recognized by Virtuoso.

So I need to modify the original property data in CSV files before Yueqiao modifies the code for adding "^^xsd:dateTime".
