### ISSUE TITLE
The "coordinate" property cannot be rendered using a geographically-specific format for sessions & events.(TheSessionDB)

### ISSUE THREAD

**Issue by candlecao** [DDMAL/linkedmusic-datalake#148]
Such as:
`Point(-34.56250000 -58.45833206)`(longitude and latitude).

If we can render this, may be in the future, we can realize some query based on geographical information system.

**Comment by candlecao** [comment]
We may refer to https://www.bobdc.com/blog/geosparql1/

**Comment by candlecao** [comment]
ChatGPT gave this format:
```
@prefix ns1: <http://www.wikidata.org/prop/direct/> .
@prefix geo: <http://www.w3.org/2003/01/geo/wgs84_pos#> .

<https://thesession.org/events/1> ns1:P625 [ 
    geo:lat "55.85637283"^^xsd:float ;
    geo:long "-4.25716591"^^xsd:float 
] .

<https://thesession.org/events/10> ns1:P625 [ 
    geo:lat "55.20029831"^^xsd:float ;
    geo:long "-6.25256252"^^xsd:float 
] .
```

**Comment by candlecao** [comment]
Please use this format:
such as
```
@prefix ex: <http://example.org/places#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix geo: <http://www.opengis.net/ont/geosparql#> .

ex:New_York a geo:Feature ;
    geo:geometry "POINT(-74.005974 40.712776)"^^geo:wktLiteral .
ex:Los_Angeles a geo:Feature ;
    geo:geometry "POINT(-118.243683 34.052235)"^^geo:wktLiteral . 
```
instead of 
```
@prefix ns1: <http://www.wikidata.org/prop/direct/> .
<https://thesession.org/events/754> ns1:P625 "(54.25597000 -5.94771004)"^^wgs:Point .
```
@Yueqiao12Zhang

**Comment by candlecao** [comment]
I used regular expression in Visual Studio Code temporarily:
Find: `(P625 "Point\([^)]+\)")`
Replace: `$1^^geo:wktLiteral`

**Comment by candlecao** [comment]
However, after the Find-Replace, I found more mistakes in the values of `wdt:P625`.
For example,
```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT distinct (DATATYPE(?value) AS ?datatype)
WHERE {
  ?subject wdt:P625 ?value .
  BIND(wdt:P625 AS ?property)
}
```
We may talk over it. @Yueqiao12Zhang

**Comment by candlecao** [comment]
<img width="899" alt="image" src="https://github.com/user-attachments/assets/689fdc7c-c7d8-4abe-aead-687641dfc1df">

**Comment by candlecao** [comment]
In our original data there are events which have no coordinate:
<img width="1373" alt="Screenshot 2024-09-06 at 09 41 49" src="https://github.com/user-attachments/assets/1582defb-c95c-43fa-aa8c-0d2d7075fa5c">
@Yueqiao12Zhang

**Comment by fujinaga** [comment]
If there's no location information in the database, there's nothing we can do.

**Comment by candlecao** [comment]
Eventually, we can use this format to render the coordinate info:
eg:
```
@prefix geo: <http://www.opengis.net/ont/geosparql#> .
@prefix wdt: <http://www.wikidata.org/prop/direct/> .
<https://thesession.org/events/1> wdt:P625 "POINT(55.85637283 -4.25716591)"^^geo:wktLiteral .
```
