### ISSUE TITLE
Cannot open the file: MusicBrainz releases

### ISSUE THREAD

**Issue by Yueqiao12Zhang** [DDMAL/linkedmusic-datalake#155]
The csv2rdf script takes too much memories (the kernel returns Killed: 9 after running the program for a long time), when working with the releases data dumps.

**Comment by dchiller** [comment]
Could you post the traceback here?

**Comment by Yueqiao12Zhang** [comment]
Yes. I will copy the error message from the lab Mac after the meeting.

**Comment by Yueqiao12Zhang** [comment]
```
CHUNK_SIZE = 10000

if __name__ == "__main__":

    # the file must be from MusicBrainz's JSON data dumps.
    chunk = []

    with open(inputpath, "r", encoding="utf-8") as f:
        print(1) # It does not reach this line.
        for line in f:
            line_data = json.loads(line)  # Parse each line as a JSON object
            chunk.append(line_data)  # Add the JSON object to the current chunk

            # When the chunk reaches the desired size, process it
            if len(chunk) == CHUNK_SIZE:
                print(2)
                extract(chunk, {})
                chunk.clear()  # Reset the chunk
                convert_dict_to_csv(values)

            values.clear()

        # Process any remaining data in the last chunk
        if chunk:
            extract(chunk, {})
            chunk.clear()
            convert_dict_to_csv(values)
```

**Comment by Yueqiao12Zhang** [comment]
(local) DDMAL-004:csv local$ python3 convert_to_csv.py ../data/raw/extracted_jsonl/mbdump/release release
[1]+  Terminated: 15          python3 convert_to_csv.py ../data/raw/extracted_jsonl/mbdump/release release
Killed: 9

**Comment by Yueqiao12Zhang** [comment]
Python does not return an error message.

**Comment by dchiller** [comment]
And so you know the place where it is erroring because it doesn't reach the print statement?

**Comment by Yueqiao12Zhang** [comment]
> And so you know the place where it is erroring because it doesn't reach the print statement?

Yes, 

> Where is the python file you are running?

/csv2rdf/csv2rdf_single_subject.py

**Comment by Yueqiao12Zhang** [comment]
Problem solved! Very dump mistake 😭

**Comment by fujinaga** [comment]
> Problem solved! Very dump mistake 😭

Great! No issues, we all make silly coding errors.
