### ISSUE TITLE
The namespace in generating RDF is incorrect.

### ISSUE THREAD

**Issue by Yueqiao12Zhang** [DDMAL/linkedmusic-datalake#163]
Change `ns1, ns2, ...` to `wd, wdt, ...`

**Comment by Yueqiao12Zhang** [comment]
Test for adding "wd" and "wdt": it significantly increases the execution time.

**Comment by fujinaga** [comment]
> What are the special namespaces that needs renaming? @candlecao @fujinaga

Anywhere you use Wikidata entities and properties:
@prefix wd: <http://www.wikidata.org/entity/>  .
@prefix wdt: <http://www.wikidata.org/prop/direct/> .

Note that it is not incorrect to use ns1/ns2, it seems that the use of wd/wdt is a common practice.
