### ISSUE TITLE
The value of property "artist" of recording is not definitely string.(TheSession)

### ISSUE THREAD

**Issue by candlecao** [DDMAL/linkedmusic-datalake#172]
For example:
![Screenshot 2024-09-03 at 21 38 54](https://github.com/user-attachments/assets/10694e58-3683-413c-8794-d5829009c6d4)
![Screenshot 2024-09-03 at 21 39 51](https://github.com/user-attachments/assets/2acccf2f-9923-4a35-a943-69dfb826d3a8)
--It is now actually an integer; it should be "1651"-- a string. Maybe we should adjust the code.

**Comment by Yueqiao12Zhang** [comment]
This will be fixed together with the datetime and coordinate recognition.
