### ISSUE TITLE
TheSession: Mode of tune is not reconciled.

### ISSUE THREAD

**Issue by candlecao** [DDMAL/linkedmusic-datalake#176]
<img width="1315" alt="image" src="https://github.com/user-attachments/assets/600e8223-2f6a-4cc8-8cbc-97100b68c8cc">

**Comment by dchiller** [comment]
I don't think wikidata has items for transposed modes. Perhaps a place that we need to make new items.

**Comment by Yueqiao12Zhang** [comment]
I assume that we leave those transposed modes unreconciled for now until we add new entries to Wikidata?

**Comment by fujinaga** [comment]
Yes, but do store the string name (e.g., "A dorian") in the RDF database.
