### ISSUE TITLE
Special number characters are not recognized in python.

### ISSUE THREAD

**Issue by Yueqiao12Zhang** [DDMAL/linkedmusic-datalake#183]
In my csv2rdf script, I use isdigit() to check for number characters automatically. However, it recognizes exponential characters like 0³, and circled characters like ⑦ as integers, while the RDFLib is not able to convert those to integer type in an RDF graph. Is there any way to recognize only pure integers in python?

**Comment by fujinaga** [comment]
Don't try to automatically determine whether a column is a number or a sting. Do this manually for each column. Maybe OpenRefine can help?

**Comment by Yueqiao12Zhang** [comment]
OpenRefine does not help since we need to specify each column. I will add a feature to specify certain special columns.

**Comment by fujinaga** [comment]
Have you started using OpenRefine API yet? Once you figured out how to do things manually, you may direst certain tasks via the API.

**Comment by Yueqiao12Zhang** [comment]
Using OpenRefine API is not realistic since 99% of the reconciliation work should involve human inspection.

**Comment by Yueqiao12Zhang** [comment]
Other graph editing work that are done in OpenRefine can be replaced using Pandas.

**Comment by fujinaga** [comment]
I'm talking about OpenRefine API after the initial conversion.
The next time, we import from a database, there should be very little interaction, except for changed or new entries since the last import.

**Comment by fujinaga** [comment]
We can use Pandas or any other custom editing of CVS files, but I want to keep it as simple as possible.
