### ISSUE TITLE
There is no archive for the manually reconciled entries for MusicBrainz

### ISSUE THREAD

**Issue by candlecao** [DDMAL/linkedmusic-datalake#194]
This issue follows #186 
Especially those "sub-types" for the entities are more or less reconciled manually. For example,
e.g.: type of area:

<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">

<style>

</style>
</head>
<body>

type | type_uri
-- | --
city | https://www.wikidata.org/wiki/Q515
country | https://www.wikidata.org/wiki/Q6256
county | https://www.wikidata.org/wiki/Q28575
district | https://www.wikidata.org/wiki/Q149621
Indigenous territory / reserve |  
island | https://www.wikidata.org/wiki/Q23442
mahakuma | https://www.wikidata.org/wiki/Q15637757
military base | https://www.wikidata.org/wiki/Q245016
municipality | https://www.wikidata.org/wiki/Q15284

</body>

</html>

**Comment by candlecao** [comment]
The archive should be put in linkedmusic-datalake/musicbrainz/data/reconciledEntries/archiveForManuallyReconciledEntries.xlsx

**Comment by candlecao** [comment]
> Does OpenRefine not have an output for this?

I believe OpenRefine can output this. But what I'm suggesting is that we store those manually reconciled records. This way, in the future, when updating the database, we don't need to manually reconcile them again.

**Comment by dchiller** [comment]
I don't think I totally understand the use case. Is the point that we have reconciled the various entities listed above (city, district, etc.) in a particular dataset with Wikidata, we have done this reconciliation manually, and we want to be able to repeat that reconciliation with updated data/new datasets, etc?

How do we currently support reconciliation of updated data?

**Comment by candlecao** [comment]
https://github.com/DDMAL/linkedmusic-datalake/tree/main/ArchiveForReconciledEntries
Please check this "archive"--as a particular dataset you mentioned.

_Is the point that we have reconciled the various entities listed above (city, district, etc.) in a particular dataset with Wikidata, we have done this reconciliation manually,_ 
--Yes.

_and we want to be able to repeat that reconciliation with updated data/new datasets_
--I don't quite understand this sentence. Anyway, we have this archive so that next time we won't need to manually reconcile again.

_How do we currently support reconciliation of updated data?_
--This is an issue to be solved or in further discussion: https://github.com/DDMAL/linkedmusic-datalake/issues/144
