### ISSUE TITLE
The new generated RDF data of MusicBrainz is too large to be uploaded to Virtuoso Staging.

### ISSUE THREAD

**Issue by candlecao** [DDMAL/linkedmusic-datalake#195]
It's 3.4GB.
![image](https://github.com/user-attachments/assets/b2321f34-4b25-4b6b-a546-bb25de49748d)

Then I tried to upload it to local Virtuoso of Docker, it even prompted 
![image](https://github.com/user-attachments/assets/4ff36ff6-855b-4f0b-9813-76bbabd650ed)
when I clicked on Upload:
![image](https://github.com/user-attachments/assets/d7f70833-7286-48de-83e3-c998beeada17)

**Comment by fujinaga** [comment]
3.4GB is not large for a database. Please find an alternative way for uploading the data.
