### ISSUE TITLE
I found an OpenLink Virtuoso specific ChatGpt, but I don't know how to use that with my API key

### ISSUE THREAD

**Issue by candlecao** [DDMAL/linkedmusic-datalake#197]
https://linkeddata.uriburner.com/chat/

It prompted:
SECURITY:401: [mismatched_organization] OpenAI-Organization header should match organization for API key
<img width="1459" alt="image" src="https://github.com/user-attachments/assets/a03663e9-416f-4078-901e-4ec47827f57d">

@kunfang98927 Hi, Kun, could you please help?

**Comment by kunfang98927** [comment]
Sorry, but I don't know how this platform is related to ChatGPT, and whether you actually have permission to use this service directly with just your OpenAI API key. I tried using my API key but got the same error message as you. You should probably look for any documentation on the platform.

**Comment by candlecao** [comment]
Thank you all the same, Kun. @kunfang98927

**Comment by candlecao** [comment]
It finally worked out. It turned out that I have to buy the credit on my OpenAI account before it work out.
![image](https://github.com/user-attachments/assets/0c057e22-0306-4d4e-b9e1-15cec16547e0)
