### ISSUE TITLE
Re-extract CantusDB data and reconcile without changing original mode data

### ISSUE THREAD

**Issue by dchiller** [DDMAL/linkedmusic-datalake#28]
We want to include the original mode data from CantusDB (1, 2, 3, etc.) and not map to greek names.

**Comment by jacobdgm** [comment]
The original mode data is there! The greek names were provided in addition. Just use the values in the "mode" column, and ignore the "mode_name" column. I can leave this column out entirely in future exports.

Closing this - if more work is required on the DataLake end, feel free to reopen.

**Comment by dchiller** [comment]
Reopening: The original mode names are not included in the reconciled json-ld, so even if they are included in the original data dump, we want to track it being re-reconciled.

> I can leave this column out entirely in future exports.

Please do...I think after last week I am realizing it is important to have the original and only the original data in the initial extracts, so that there is. a clear dividing line throughout the process what is "original" and what is "added".

**Comment by jacobdgm** [comment]
> Please do...I think after last week I am realizing it is important to have the original and only the original data in the initial extracts, so that there is. a clear dividing line throughout the process what is "original" and what is "added".

I'll also leave out "Anonymous" (some of the chants may have been composed by Hildegard anyways) then, and the chant detail and source detail URIs? For all of these, I did some degree of tweaking/hardcoding rather than just including a value stored in the database.

**Comment by dchiller** [comment]
> I'll also leave out "Anonymous" (some of the chants may have been composed by Hildegard anyways) then

Amazing!

> the chant detail and source detail URIs

Oops, can you say more about this? I think we do want to include URI's but I would have thought that these would be in the database...

**Comment by jacobdgm** [comment]
These are not stored in the database per se - whenever we need to display links, we use `{% url 'source-detail' source.id %}` etc. in our template. So strictly speaking, only the ID is stored in the database.

**Comment by jacobdgm** [comment]
See, e.g., https://github.com/DDMAL/linkedmusic-datalake/discussions/11#discussioncomment-7147481:
```python
for chant in chants:
    print(f'"{chant.id}",...,"https://cantusdatabase.org/chant/{chant.id}","https://cantusdatabase.org/source/{chant.source.id}",...)
```

**Comment by dchiller** [comment]
I see. thanks. tagging in @malajvan and @homework36 because possibly relevant to the discussion we just had. 

I think you could just leave them as ID's and then they would get expanded to the full URI using the context created with the JSON-LD? But @malajvan would know better.

**Comment by jacobdgm** [comment]
so I'll also include a column for `source_id`, so the source detail URI can be generated. But otherwise, I'll not include literal URIs, putative composers, or greek modes.
