### ISSUE TITLE
Generalization for the convert_to_csv script for MusicBrainz

### ISSUE THREAD

**Issue by Yueqiao12Zhang** [DDMAL/linkedmusic-datalake#58]
Generalize the script.
User does not have to go inside the script to change the input file. 
OpenRefine procedures should be avoided as much as possible, and the issue should be able to skip OpenRefine for MusicBrainz.

**Comment by dchiller** [comment]
> Generalize the script.

Generalize in what way? If I look a the linked PR, it looks like you are generalizing in terms of being able to handle multiple entity types...is that what you mean? If so, can you specify that here?

> OpenRefine procedures should be avoided as much as possible, and the issue should be able to skip OpenRefine for MusicBrainz.

I don't see anything in the linked PR that would suggest that OpenRefine procedures are avoided or not avoided. Can you explain this?
