### ISSUE TITLE
A illustration of CSV2RDF using Python plus RDFLib--taking MusicBrainz as Example

### ISSUE THREAD

**Issue by candlecao** [DDMAL/linkedmusic-datalake#71]
Yueqiao will Illustrate this to Junjun, who will rehearse and recap it before integrating it as one of the methods about CSV2RDF into Virtuoso, additionally, for documentation.

**Comment by candlecao** [comment]
The illustration is done on Jun 20.
Some questions to ask Yueqiao:
The json files of test_area/event/instrument/label/recording seem not in quite valid format, why?
They are like:
```
{}
{}
{}
```
...

**Comment by candlecao** [comment]
Here is the brief notes for your work. You may notice it(@Yueqiao12Zhang ):
**II.CSV to Turtle(a serialized RDF) before Uploading to Virtuoso**/ [Several Ways of CSV to Virtuoso LinkedData...](https://github.com/DDMAL/linkedmusic-datalake/wiki/Several-Ways-of-CSV-to-Virtuoso-LinkedData%E2%80%90%E2%80%90account-for-the-2nd-way-we-are-in(updating-by-adding-more-ways)
)

**Comment by Yueqiao12Zhang** [comment]
> The illustration is done on Jun 20. Some questions to confirm with / ask Yueqiao:
> 
> 1. The json files of test_area/event/instrument/label/recording seem not in quite valid format, why and doesn't it matter?
> 
> They are like:
> 
> ```
> {}
> {}
> {}
> ```
> 
> ...
> 
> 2. In terminal, with respect to executing `python3 get_relations.py MusicBrainz/*.csv`, how is this syntax of command defined? So it is with the syntax of `python3 csv2rdf_single_subject.py mapping.json area.csv artist.csv genre.csv recording.csv` ...

1. This file is in JSON lines format. They are not recognized by the VS code JSON formatter. My code deals with the raw input format, so there's nothing to change and worry about.

2. Yes, they should be equivalent.

**Comment by candlecao** [comment]
Finished.
