### ISSUE TITLE
Simssa DB data processing

### ISSUE THREAD

**Issue by Yueqiao12Zhang** [DDMAL/linkedmusic-datalake#75]
This issue starts with retrieving the Simssa DB data dumps. Can I use the files in [https://github.com/ELVIS-Project/simssadb/tree/develop/sample_data_for_SIMSSA_DB](url)? If yes, what specific files should be used?

**Comment by Yueqiao12Zhang** [comment]
In the original folder, there is a left over SQL dump. I did not find the SQL dump in the simssa DB github website, but I found a few CSVs (seems to be small snippets). For example, [https://github.com/ELVIS-Project/simssadb/blob/develop/sample_data_for_SIMSSA_DB/JLSDD/JLSDD%20(corr%20IL).csv](url).

**Comment by fujinaga** [comment]
Because we are just experimenting at this stage, you can use any or all of the available data. You can certainly start with [https://github.com/ELVIS-Project/simssadb/blob/develop/sample_data_for_SIMSSA_DB/JLSDD/JLSDD%20(corr%20IL).csv](url) and see what kind of issues are involved.

**Comment by Yueqiao12Zhang** [comment]
In the JLSDD CSV, there's no IDs for any attribute including the key attribute. In the SQL dump, there is at least one ID for all tables to connect them to other tables. If I start by using this sample, then the reconciliation step would be different when we move on to the real set of data.

**Comment by fujinaga** [comment]
Please follow or update the procedure described by @malajvan in [https://github.com/DDMAL/linkedmusic-datalake/blob/main/simssadb/simssadb_pipeline.md](url)

**Comment by Yueqiao12Zhang** [comment]
I tried the same procedure using my local PostgreSQL.app, but since I did not find the newest SQL file, I still use the old CSV from Van. Therefore I got the same CSV as output. I did some optimization according to the specifications of my CSV2RDF script.

**Comment by fujinaga** [comment]
You should be able to get the SQL files from [https://github.com/ELVIS-Project/simssadb
](url) or [https://github.com/DDMAL/docker-simssadb](url). Ask the grad students for help, e.g., @lucasmarchd01
