### ISSUE TITLE
MusicBrainz RDF needs some improvements

### ISSUE THREAD

**Issue by candlecao** [DDMAL/linkedmusic-datalake#79]
2. "artist-credit_artist_genres_id" is not embodied at the front end, removing "artist-credit_artist_genres_id" column in recording.csv. Since for each entity type, we can track it to other CSVs using it's ID, so there's no need to extract further. Such as artist_genre_id in recording's CSV, we don't need this column since we have an genre_id for artist in artist's CSV. I inspected all CSVs and there is no special case for exception. 

3. Fixing many incorrectly reconciled cells. 
eg., https://musicbrainz.org/genres/eacfa027-2fad-413f-a2f1-80fa43674f0b, https://musicbrainz.org/genres/cc28f5aa-5e19-487c-88e1-e56b022f1fdd, https://musicbrainz.org/genres/0e3fc579-2d24-4f20-9dae-736e1ec78798)

They all need to perform the change: /genres/ -> /genre/. They will be fixed in the conversion script.

4. the rdf:type of "recording" https://www.wikidata.org/wiki/Q155171. Recording is changed to https://www.wikidata.org/wiki/Q15975575.

5. the rdf:type of "area" https://www.wikidata.org/wiki/Q11500. Area is changed to https://www.wikidata.org/wiki/Q2221906.

6. Property of area is changed to https://www.wikidata.org/wiki/Property:P276.

7. Relations_wiki property change: P1687 -> P2888 (exact match) of Wikidata. Better matching the virtuoso and reasoning machine pattern.

8. In Wikidata and SPARQL, as to property, the standard format is http://www.wikidata.org/prop/direct/Pxxx, instead of https://www.wikidata.org/wiki/Property:Pxxx.

In a similar way, as to entity, the standard format is http://www.wikidata.org/entity/Qxxx, instead of https://www.wikidata.org/wiki/Qxxx. 

For these format changes, they also apply to all other databases' mappings.

9. Use music genre Q188451 rather than genre Q483394 for https://musicbrainz.org/doc/Genre.

10. Re-structure the repository:
- add urllib3 and bs4 to the dependency management documentation and remove the poetry.lock and pyproject.toml inside the Musicbrainz repo.
- move the test files, scripts, and docs around to match a standard pattern of other database repositories.

11. Output RDF subjects should be specific about their types when they are not URIs or Literals, such as Integers and Booleans.

**Comment by candlecao** [comment]
1. Only part of Data entities is open to the Public Domain from the [postgres-dumps#musicbrainz](https://metabrainz.org/datasets/postgres-dumps#musicbrainz).  A complete list of entities is: [Entities List: MusicBrainz_Database](https://musicbrainz.org/doc/MusicBrainz_Database). Some entities like Genre are not distributed there. However, one can download from the API in format of XML, see [https://musicbrainz.org/doc/MusicBrainz_API](https://musicbrainz.org/doc/MusicBrainz_API).
2. ...

**Comment by candlecao** [comment]
**Memorandom**
As to some attributes:
1. relations_wiki: denote the URI of the corresponding entity of MusicBrainz.
> But why there is no such attribute for "Recordings"? @Yueqiao12Zhang

**Comment by Yueqiao12Zhang** [comment]
> 1. Only part of Data entities is open to the Public Domain from the [postgres-dumps#musicbrainz](https://metabrainz.org/datasets/postgres-dumps#musicbrainz).  While a complete list of entities is shown as: [Entities List: MusicBrainz_Database](https://musicbrainz.org/doc/MusicBrainz_Database). Some entities like "Genre" are not distributed there. However, one can download from the API in format of XML, see https://musicbrainz.org/doc/MusicBrainz_API.
> 3. Missed some properties(of entity) such like:
> 
> > Take recording as example: aliases, rating(is it necessary?), tags
> > > rating:
> 
> ```
> "rating": {
>         "value": null,
>         "votes-count": 0
>     }
> ```
Since there is no 'name' and 'id' attribute for rating, it is not extracted.

> 4. Account for some attribute terms such as:
>    artist-credit_artist_name--why is it "artist-credit"?
Sometimes it is different than 'artist'. 'artist-credit' is a separate entry in the JSON file apart from 'artist'.
> 5. About genre and artist-genre! eg:https://musicbrainz.org/recording/f28b2394-bd5d-4f0c-a0de-55ce015a5c57
> 
> > "artist-credit_artist_genres_id" is not embodied at the front end!
> > There is no need to add "artist-credit_artist_genres_id" to "recording".
I will remove.
> 6. eg: MBID of "recording" corresponds to recording_id in the reconciled CSV!?
Yes.
> 7. Why are some not reconciled? Eg: genre(only using the original URL of MusicBrainz, some of which genre are not accessible: eg., https://musicbrainz.org/genres/eacfa027-2fad-413f-a2f1-80fa43674f0b, https://musicbrainz.org/genres/cc28f5aa-5e19-487c-88e1-e56b022f1fdd, https://musicbrainz.org/genres/0e3fc579-2d24-4f20-9dae-736e1ec78798)
> 
> > Yueqiao: /genres/ -> /genre/
I will fix this.
> 8. Proofreading on Reconciliation:
>    Should we reconcile with other vocabularies like schema.org!?
> 
> > 8.1 class (shall we also define the type using the intro-page on the original website for each entity!?)
> > rdf:type -> wdt:P31(instance of)?!
> > > Is the rdf:type of "recording" https://www.wikidata.org/wiki/Q155171?(I don't think so) Or we use https://musicbrainz.org/doc/Recording directly.
> > > Is the rdf:type of "area" https://www.wikidata.org/wiki/Q11500?, which is more like "面积" instead of a geographically delineated spatial range “place/area”. What about [geographic location (Q2221906)](https://www.wikidata.org/wiki/Q2221906) or [place (Q98929991)](https://www.wikidata.org/wiki/Q98929991)
> 
> > 8.2 property
> 
> 11. As to property of length of recording, what is the unit of measurement? It should be embodied in RDF.
> 
> > Eg: https://musicbrainz.org/recording/565de6d8-f93f-4b44-97e2-c1f3ffc2410a
> > > Length: 4:24 from webpage
> > > `"length": 264000` from json
> 
> 13. As to property of video of recording, what is the unit of measurement? ...
> 
> > eg:
> 
> ```
> <https://musicbrainz.org/event/002ca3ef-52f7-4e8e-a239-012f8887f6c7> a ns3:Q1656682 ;
>     ns2:Type "ef55e8d7-3d00-394a-8012-f5506a29ff0b" ;
>     ns3:Q30108381 "False"^^xsd:boolean .
> ```
> 
> @Yueqiao12Zhang

**Comment by candlecao** [comment]
Re-inspection:

1. As for entity of genre, if we reconcile between a URI of MusicBrainz and that of Wikidata and we want to keep both of them, we can use "P2888 (exact match)" of Wikidata instead of "https://www.wikidata.org/wiki/Property:P1687"(维基数据属性)

**Comment by candlecao** [comment]
Suggestion:
Next time, try using namespace prefixes familiar to the public in the output RDF turtle format, such as
```
PREFIX wd:<http://www.wikidata.org/entity/>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
```
Can that be done automatically by adjusting the code?
I think we had better unify the namespace prefix across multiple graphs.

@Yueqiao12Zhang

**Comment by Yueqiao12Zhang** [comment]
> Suggestion: Next time, try using namespace prefixes familiar to the public in the output RDF turtle format, such as
> 
> ```
> PREFIX wd:<http://www.wikidata.org/entity/>
> PREFIX wdt:<http://www.wikidata.org/prop/direct/>
> ```
> 
> Can that be done automatically by adjusting the code? I think we had better unify the namespace prefix across multiple graphs.
> 
> @Yueqiao12Zhang

If the code let us customize the namespace names, then it is not possible to generate the rdf automatically for all the databases.

**Comment by candlecao** [comment]
The value of genres_id property of recording entity is not reconciled.
@Yueqiao12Zhang

**Comment by candlecao** [comment]
I figured out a simple way:
```
SELECT DISTINCT ?classOfDomain ?property ?classOfRange
FROM <http://sample/musicbrainz/reconciled>
WHERE {
  ?subject a ?classOfDomain.
  ?subject ?property ?object .
  ?object a ?classOfRange.
}
```
