### ISSUE TITLE
AcousticBrainz raw json to csv

### ISSUE THREAD

**Issue by Yueqiao12Zhang** [DDMAL/linkedmusic-datalake#82]
AcousticBrainz is a database full of stats for recordings. This issue investigates how to convert all records in raw json format files into a single CSV of recordings.

**Comment by fujinaga** [comment]
You can start with their "Sample downloads" containing 100,000: [https://acousticbrainz.org/download](url)

**Comment by Yueqiao12Zhang** [comment]
I am starting with this dump.
