### ISSUE TITLE
OpenRefine Reconciliation Documentation (for The Session)

### ISSUE THREAD

**Issue by candlecao** [DDMAL/linkedmusic-datalake#93]
Document the process for reconciling CSV files using OpenRefine—for The Session.

**Comment by Yueqiao12Zhang** [comment]
https://github.com/DDMAL/linkedmusic-datalake/blob/main/thesession/README.md
https://github.com/DDMAL/linkedmusic-datalake/blob/main/thesession/data/reconciled/reconcile_procedures.md

**Comment by fujinaga** [comment]
@Yueqiao12Zhang Looking great! Can you add the procedure of what to do next, i.e., go to cvs2rdf ?
@candlecao Can you start from scratch and create the CVS files on your own? Create new issues, if you run into problems (issues).

**Comment by Yueqiao12Zhang** [comment]
> @Yueqiao12Zhang Looking great! Can you add the procedure of what to do next, i.e., go to cvs2rdf ?

All csv2rdf procedures are in https://github.com/DDMAL/linkedmusic-datalake/tree/csv2rdf-doc-review/csv2rdf.
