### ISSUE TITLE
Determine how to indicate confidence levels for triples(statements).

### ISSUE THREAD

**Issue by candlecao** [DDMAL/linkedmusic-datalake#95]
Had better not use blank-nodes.

**Comment by candlecao** [comment]
Comparatively, named graphs may be more preferable to blank nodes, because blank-nodes are limited to internal usage, while named graphs are more "exterior" or open, findable by visiting the URI.
@fujinaga Hi Ich, is this understanding right?

**Comment by fujinaga** [comment]
Yes, that’s one of the reasons.
