### ISSUE TITLE
Examine the reconciliation and the output RDF for The Session Database

### ISSUE THREAD

**Issue by candlecao** [DDMAL/linkedmusic-datalake#98]
Check and accept RDF for The Session Database.

**Comment by candlecao** [comment]
Some to be review:
address-> street address (P6375)
town-> located in the administrative territorial entity (P131)
area-> location (P276)

Some are wrong:
    ```
    "latitude": "http://www.wikidata.org/prop/direct/P6261"
    "longitude": "http://www.wikidata.org/prop/direct/P6260"
```
P6261,6260 are galactic coordinates. We should use wdt:P625 and put the two attributes's value together:

**Comment by candlecao** [comment]
About embedded data, See this example:
<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">

<style>

</style>
</head>
<body>


recording_id | artist | recording | recording_wiki | track | number | tune | tune_id
-- | -- | -- | -- | -- | -- | -- | --
https://thesession.org/recordings/3720 | 1651 | Cast A Bell |   | 1 | 1 | Kettledrum | https://thesession.org/tunes/14408
https://thesession.org/recordings/3720 | 1651 | Cast A Bell |   | 2 | 1 | Maiden Lane | https://thesession.org/tunes/13727
https://thesession.org/recordings/3720 | 1651 | Cast A Bell |   | 2 | 2 | Chirping Of The Nightingale |  
https://thesession.org/recordings/3720 | 1651 | Cast A Bell |   | 2 | 3 | Chirping Of The Lark |  
https://thesession.org/recordings/3720 | 1651 | Cast A Bell |   | 3 | 1 | Kemp's | https://thesession.org/tunes/10151
https://thesession.org/recordings/3720 | 1651 | Cast A Bell |   | 3 | 2 | Picking Of Sticks |  
https://thesession.org/recordings/3720 | 1651 | Cast A Bell |   | 3 | 3 | Woodicock |  
https://thesession.org/recordings/3720 | 1651 | Cast A Bell |   | 4 | 1 | Lady Lie Near Me |  
https://thesession.org/recordings/3720 | 1651 | Cast A Bell |   | 4 | 2 | Beggar Boy |  
https://thesession.org/recordings/3720 | 1651 | Cast A Bell |   | 5 | 1 | Millfield |  
https://thesession.org/recordings/3720 | 1651 | Cast A Bell |   | 5 | 2 | Grimstock | https://thesession.org/tunes/14292



</body>

</html>



A recording_id has different tunes, each tune corresponds to a track property and a number property. As to such structure, one of the methods is using the empty nodes. So the turtle data structure should be like:
```
<https://thesession.org/recordings/3720> wdt:P1625 [
wdt:P51 <https://thesession.org/tunes/14408>;
wdt:P658 "1";
wdt:P1114 "1"
] .

```

**Comment by dchiller** [comment]
> "https://thesession.org/tunebooks"

This is a 404.

**Comment by candlecao** [comment]
GRAPH <http://example.org/graph/tune_in_recording> {
   ex:Colley's ex: track "12";
                       ex:number "1";
                        ex:correspondsToRecording <https://thesession.org/recordings/1032>.
}

ex:<https://thesession.org/recordings/1032> ex:tune <http://example.org/graph/tune_in_recording#Clooey's>.

**Comment by candlecao** [comment]
> > 2.2 "artist": "http://www.wikidata.org/prop/direct/P5489", -> "http://www.wikidata.org/prop/direct/P50"
> 
> [P50](http://www.wikidata.org/prop/direct/P50) is "main creator(s) of a written work". So probably not for recordings.
> 
> > 2.5 "tunebooks":"http://www.wikidata.org/entity/Q66382988", -> "https://thesession.org/tunebooks"
> 
> "https://thesession.org/tunebooks" is a 404. Seems like there are WikiData properties, too, that are for this type of relationship... eg. https://www.wikidata.org/wiki/Property:P1433

Hi @dchiller . Thank you. Got it. We will refer to your advice.
